### PR TITLE
Make build work on all platforms(most of them)

### PR DESCRIPTION
**Pull request by ramlmn**
Some terminal emulators don't seem to like nested commands and `;`.

### CODE REVIEW

**Comment by ramlmn** [comment]
Fixes some issues concerning [https://github.com/GoogleChrome/devsummit/issues/44#issuecomment-258186236](https://github.com/GoogleChrome/devsummit/issues/44#issuecomment-258186236)

**Comment by ramlmn** [comment]
I know you are not thinking of making the build work elsewhere anytime soon, but I think it's better that taking any more build related issues. \cc @paullewis

**Comment by paullewis** [comment]
Thanks... again! #heroicwork

**Comment by ramlmn** [comment]
And again, please have a look at #34. \cc @paullewis

**Pull request merged**
