### PR TITLE
Live now & next, including livestream

### PR DESCRIPTION
**Pull request by jakearchibald**
Before the conference https://deploy-preview-347--cds2019.netlify.com/devsummit/?now=1573487000000.

"Happening now" rather than "Live now" since it isn't on the livestream. The "up next" box only ever covers livestream-relevant content (do you think this is a good idea?).

During registration: https://deploy-preview-347--cds2019.netlify.com/devsummit/?now=1573488000000

A session: https://deploy-preview-347--cds2019.netlify.com/devsummit/?now=1573495440000.

A session with one speaker https://deploy-preview-347--cds2019.netlify.com/devsummit/?now=1573503300000.

A session with lots of speakers https://deploy-preview-347--cds2019.netlify.com/devsummit/?now=1573599600000.

A break https://deploy-preview-347--cds2019.netlify.com/devsummit/?now=1573500900000.

Social hour https://deploy-preview-347--cds2019.netlify.com/devsummit/?now=1573525500000.

Between days https://deploy-preview-347--cds2019.netlify.com/devsummit/?now=1573547100000.

Conference over https://deploy-preview-347--cds2019.netlify.com/devsummit/?now=1573609600000.

### CODE REVIEW

**Comment by argyleink** [comment]
nice work, dark mode for free looks great. 
thanks for animating live now! great pacing on it, love it.
thanks also for sharing all these states, thinking them out, and making the design surface of them so easy for me to see and play with. 

here's a few design nits:
- border radius is missing on the top right and bottom right corners of the "up next" box
- i noticed the next update text isnt evenly spaced between the "up next" text and the "in 2 hrs" text. i corrected it with visbug, looks like a task that needs done visually. can you make sure there's even space between those 3 text items? 
Screen Shot 2019-11-07 at 2 49 44 PM
- can you drop the font size of <rel-time> to ~15px
- speaker chips are too big on desktop, i'd like them to flow into that space more often. like the size they are on mobile feels good for this desktop here spot. let's leave this one as an open todo for me, unless you wanna stab at it in this PR?
- live now dot and text arent vertically aligned. dot it off 2px top.


before conf: 
- i like the up next box only covering live-stream items, which i assume is the same list as the schedule? it should be the schedule, so the link we provide and this mini experience are synced.
- happening now is great if it's not live content, good call. i may try and drop an icon there to show it's like "people / community" time 🤷‍♂ no task here, just thoughts.

during conf:
- header CTA should say "Live Stream" and take the user to the youtube channel for couch mode

between days:
- happening now, day 1 complete! feels off. maybe vivian has ideas here? 

it's over:
- happening now, it's over feels off too hehe. i'm also on the hook for a new comp to show this state as well (at least i want to be). i'll make the video even more featured, etc. glad the state is there for me to design with tho, thanks!

**Comment by jakearchibald** [comment]
> can you drop the font size of to ~15px

Huh?

Happy to experiment with the size of things, but if there's specific values you want, can you give me them in the same CSS unit they're currently in? Ems are important for mobile.

**Comment by jakearchibald** [comment]
Reminder to myself: the margins are bad on mobile for sessions that don't have speakers (eg breaks)

**Comment by argyleink** [comment]
> > can you drop the font size of to ~15px
> 
> Huh?
> 
> Happy to experiment with the size of things, but if there's specific values you want, can you give me them in the same CSS unit they're currently in? Ems are important for mobile.

yep, can do. i was expressing visuals without checking implementation details. i also updated the comment to properly fence the target of the ~15px request, so it's not a mystery now 🕵

**Comment by argyleink** [comment]
took care of the spacing and font size nits, a few other things too.

this one's for googlebot, @googlebot I consent.

the header CTA and some copy edits are all i think that's left?

**Comment by jakearchibald** [comment]
@argyleink Thanks for picking this up! I tweaked the breakpoints a little so the text centers at the same points other content does.

I also centered the speaker chips. It looked weird to me that it went from centered (talk title) to left aligned (speaker chips) to right aligned (next talk). Centering the speaker chips seems to fix that, but happy to change it.

**Comment by jakearchibald** [comment]
@argyleink I think we're ready to go.

I've removed the "happening now" text when it doesn't make sense.

I've made the "live stream" button link to the homepage rather than YouTube. As such, I don't display that button on the homepage itself. https://deploy-preview-347--cds2019.netlify.com/devsummit/schedule/?now=1573495440000

Also the button doesn't appear when the livestream is over.

WDYT?

**Comment by argyleink** [comment]
LGTM 👍

**Pull request merged**
