### PR TITLE
Adding date formatter that doesn't use the timezone

### PR DESCRIPTION
**Pull request by jakearchibald**
I didn't use it in the end, but is it worth keeping?

Also making the structured data less specific, which will hopefully(?) fix the off-by-one date in search results.

### CODE REVIEW

**Comment by jakearchibald** [comment]
I'm trying to find out if these dates should be UTC or local.

**Comment by surma** [comment]
> which will hopefully(?) fix the off-by-one date in search results.

From the UK, the result “Dates: Mon, Nov 11, 2019 – Wed, Nov 13, 2019” is correct, isn’t it? That’s why I assumed it was currently correct.

**Comment by jakearchibald** [comment]
I just don't see how it's figuring out it's in the SF timezone.

Anyway, I'm waiting for confirmation, but it's sounding like these dates should include the timezone.

**Comment by surma** [comment]
> I just don't see how it's figuring out it's in the SF timezone

I assumed via the location.

**Comment by jakearchibald** [comment]
Fair. Let's sit on this until we hear back from search folks on how it's supposed to work. 

Internal issue: https://buganizer.corp.google.com/issues/140547787

**Pull request closed without merging**
