### PR TITLE
Add missing border to content boxes

### PR DESCRIPTION
**Pull request by argyleink**
i tried to keep the PR focused on just borders.. but did end up nudging a shadow or 2 while i was there 😬

### CODE REVIEW

**Comment by jakearchibald** [comment]
@argyleink quick question before we merge… should these things have side borders when they're full width (as they are in the mobile view)? We could make the border just top & bottom in those cases.

**Comment by argyleink** [comment]
no borders on mobile 👍 
the pattern is essentially a light but deep box-shadow for desktop that includes a subtle border to help it pop a bit and simulate some minor lighting effects, but all that crap goes out the window for mobile where we pull lots of that depth out in favor of flat and single column layouts.

wow that was verbose... tldr; rule = no box shadow, no border

**Comment by argyleink** [comment]
and cool, i'll wait for this to merge, cuz i'm updating the schedule page shadows right now. in fact, want me to put the borders on there in that PR?

**Comment by argyleink** [comment]
goes well with #318

**Comment by jakearchibald** [comment]
@argyleink 

> no borders on mobile

But they do in this PR. Eg https://deploy-preview-304--cds2019.netlify.com/devsummit/schedule/ - the "Every session is available through…" box has 4 borders. The top & bottom border looks good IMO, but don't think it should have side borders.

**Comment by argyleink** [comment]
ooh yes, good call, i wanted to react with "no borders ONLY IF the content goes edge to edge," but i do like the borders in that deployed PR! thanks for calling it out. i'm convinced. let's keep the borders on top and bottom when content boxes goes edge to edge on mobile. 

**i'll pull latest and do a border sweep.** 
jake, i love your eagle eyes 🦅 👀 , would appreciate another review before merging

**Comment by argyleink** [comment]
@googlebot I consent.
🤷‍♂

**Comment by jakearchibald** [comment]
We still have side borders on content that's 100% width.

https://deploy-preview-304--cds2019.netlify.com/devsummit/schedule/

Screenshot 2019-10-10 at 13 08 19

The box containing the "Every session is available…" content has 4 borders, top right bottom left. It seems weird to me that it has left & right borders right up against the edge of the viewport.

image (1)

image (2)

**Comment by argyleink** [comment]
agree! lemme adjust!

**Comment by argyleink** [comment]
check again! found a bunch of instances, and even fixed a tag that was missing a border! thanks nit picking 1px with me

**Pull request merged**
