### PR TITLE
Add edits to the frameworks section

### PR DESCRIPTION
**Pull request by addyosmani**
Some minor updates to my session before I get a tweet out about it. I've also updated the graphic (original [here](http://imgur.com/a/RHURw) in case I used an incorrect gradient). Ta. cc @paullewis

### CODE REVIEW

**Comment by paullewis** [comment]
We're seeing the background more than your face in the photo... let me do a version at this end.

**Comment by paullewis** [comment]
addy-osmani

Happy with that?

**Comment by addyosmani** [comment]
Totally works for me. Thanks for getting that out so quick!

**Comment by paullewis** [comment]
Closed because I did these changes manually. Also I'm an idiot for not merging these first, then overwriting. Sorry about me.

**Pull request closed without merging**
