### PR TITLE
Goth mode

### PR DESCRIPTION
**Pull request by argyleink**
wanted to spend 30m to see how far into a dark theme i could get, got pretty far! wanted to share and save the work, get the convo started. thoughts? 

**To Do:**
- [x] update shadows (waiting on #318 to land)
- [x] fix jpgs/pngs
- [x] subdue brand promo dividers
- [x] ensure all squiggles are fixed

<br>

Screen Shot 2019-11-05 at 8 46 16 AM

### CODE REVIEW

**Comment by surma** [comment]
Cool work! I am on-board with shipping this, but there's some kinks to iron out.

Some of the colors need adjustment for WCAG contrast. The red color near the footer is... strong :D And maybe we can use `filter` to darken/desaturate most of the images, as [described by @tomyac](https://web.dev/prefers-color-scheme/). Also one squiggle is not inverted.

Also, do we wanna provide a switch to toggle dark mode? We could use the custom element provided in @tomayac’s article above, as well.

**Comment by tomayac** [comment]
I'll have a look later. FYI, `<dark-mode-toggle>` is live on [v8.dev](https://v8.dev/) if you want to see how it behaves.

**Comment by jakearchibald** [comment]
Happy to ship without the manual toggle, and add the manual toggle later. But yeah, generally this looks great. Happy to land it once the contrast issues and images are sorted.

**Comment by tomayac** [comment]
@argyleink @surma As promised I've had a look regarding adding the `<dark-mode-toggle>`. Please see my [fork](https://github.com/GoogleChrome/devsummit/commit/87da8ec4126c56cea71a16731a32c99f2cd21f95) for details. I have on purpose not created a PR, as I just want to show the baseline mechanics of how this could work.

**Comment by argyleink** [comment]
ready for QA, I think it's done or is very near completion. looks super rad, the dark shadows on the dark surfaces is hella metal 💀 🤘  

can add a manual button later? feels nice to have?

**Comment by argyleink** [comment]
thanks for the review jake! all items were tapped in the most recent 6 commits. give it another look, i think we ironed out the last issues. i checked contrast on things too, to make sure we're passing 👍

**Pull request merged**
