### PR TITLE
Titles are centred on mobile

### PR DESCRIPTION
**Pull request by jakearchibald**

### CODE REVIEW

**Comment by surma** [comment]
(@argyleink should make the final call on this)

Personal opinion: I think the all-lower-case is part of our aesthetic. We have it in the intro module and I think we should stick to it. I also think the centering feels out of place.

Playing with window sizes on this PR, I actually think we can bring back the `chrome://` even sooner, potentiall aroud 480px.

**Comment by jakearchibald** [comment]
I don't have strong feelings here. Over to you @argyleink

**Comment by argyleink** [comment]
i've got a few FGs here, thanks for giving me so much room to express them 👍 

this work looks great jake, thx! and while i like surma's thoughts, ultimately it's great as implemented (which matches designs). surma's thought on bringing in the pseudo content sooner is nice though, here's a gif of me adjusting it to `480px` (stellar eye surma). 

responsive-pseudo

I also noticed this while changing the media query for the pseudo element, some awkward duplication:

Screen Shot 2019-07-30 at 8 18 16 AM

**Comment by jakearchibald** [comment]
The duplication will be addressed by https://github.com/GoogleChrome/devsummit/issues/189.

**Pull request merged**
